*;
*MOST FREQUENT VALUE (COUNT);
*;
length IMP_PLAN_M 8;
label IMP_PLAN_M = 'Imputed: Plan miêdzynarodowy';
IMP_PLAN_M = PLAN_M;
if missing(PLAN_M) then IMP_PLAN_M = 0;
length IMP_POCZTA_G 8;
label IMP_POCZTA_G = 'Imputed: Poczta g³osowa';
IMP_POCZTA_G = POCZTA_G;
if missing(POCZTA_G) then IMP_POCZTA_G = 0;
*;
*MEAN-MAX-MIN-MEDIAN-MIDRANGE AND ROBUST ESTIMATES;
*;
label IMP_DZIENMIN = 'Imputed: Dzieñ minuty';
length IMP_DZIENMIN 8;
IMP_DZIENMIN = DZIENMIN;
if missing(DZIENMIN) then IMP_DZIENMIN = 179.76166316;
label IMP_DZIENROZ = 'Imputed: Dzieñ rozmowy';
length IMP_DZIENROZ 8;
IMP_DZIENROZ = DZIENROZ;
if missing(DZIENROZ) then IMP_DZIENROZ = 100.44084084;
label IMP_L_WIAD = 'Imputed: Liczba wiadomoœci';
length IMP_L_WIAD 8;
IMP_L_WIAD = L_WIAD;
if missing(L_WIAD) then IMP_L_WIAD = 8.1038727109;
label IMP_M_ROZM = 'Imputed: Miedzynarodowe rozmowy';
length IMP_M_ROZM 8;
IMP_M_ROZM = M_ROZM;
if missing(M_ROZM) then IMP_M_ROZM = 4.48046875;
label IMP_NOCOPL = 'Imputed: Noc op³ata';
length IMP_NOCOPL 8;
IMP_NOCOPL = NOCOPL;
if missing(NOCOPL) then IMP_NOCOPL = 9.0396638655;
label IMP_NOCROZ = 'Imputed: Noc rozmowy';
length IMP_NOCROZ 8;
IMP_NOCROZ = NOCROZ;
if missing(NOCROZ) then IMP_NOCROZ = 100.11207933;
label IMP_WIECZMIN = 'Imputed: Wieczór minuty';
length IMP_WIECZMIN 8;
IMP_WIECZMIN = WIECZMIN;
if missing(WIECZMIN) then IMP_WIECZMIN = 200.97545018;
