
---
title: "Zadanie_05"
author: "Uladzislau Darhevich"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Spis treści
Raport zawiera:

* tytuł, autora, date wykonania
* wykres kursow USD, EUR, GBP
  + Wykres zawiera dane za ostatnie 7 dni
  + Wykres znajduje sie w osobnym rozdziale raportu
  
```{r , echo=FALSE, results='hide', include=FALSE}
library(tidyverse)
library(dplyr)
library(patchwork)
library(knitr)
library(ggplot2)
library(grid)
library(ggpubr)
library(ggeasy)
getNBPData <- function(year=2021){
    
  ret <- data.frame()

  if(year>=2013){

    fileName <- paste0(year,"_NBP_data.csv")
  
    try({
      if(file.exists(fileName)){
        if(as.Date(file.info(fileName)$mtime)==Sys.Date()){
          cat(paste("Reading data from local file\n"))
          ret<-read.table(file=fileName,sep=";",dec=",",header=T,stringsAsFactor=F)
    	  colnames(ret) <- gsub("X","",colnames(ret))
	  return(ret)
	}
      }
    })
  
    cat(paste("Downloading data\n"))
  
    res <- try({
  
      d <- readLines(paste0("https://www.nbp.pl/kursy/Archiwum/archiwum_tab_a_",year,".csv"))
      d <- d[-2]
      d <- d[-c((length(d)-3):length(d))]
      tmpColnames <- strsplit(d[1],";",useBytes=T)[[1]]
      tmpColnames <- tmpColnames[-c((length(tmpColnames)-1):length(tmpColnames))]
      d <- do.call("rbind",
        lapply(strsplit(d[-1],";"),
        function(x){
          matrix(as.numeric(gsub(",",".",x[-c((length(x)-1):length(x))])),nrow=1)
        })
      )
      colnames(d) <- tmpColnames
      d <- as.data.frame(d)
      
      d$data <- as.Date(as.character(d$data),format="%Y%m%d")
      ret <- d
      write.table(ret,file=fileName,sep=";",dec=",",row.names=F)
    
    },silent=T)
  
    if(inherits(res,"try-error")){
      cat(paste("An error occurred while downloading data!!!\n")) 
    }
  

  }

  return(ret)

}
```

# Rozdział 1. Wykres kursów USD, EUR, GBP
```{r, echo=FALSE}

ret <- getNBPData(2021)
ret <- ret[,grep("data|EUR|USD|GBP",colnames(ret))] 
ret$data <- as.Date(ret$data)
ret<- tail(ret,7)
colors <- c("USD" = "darkgreen", "EUR" = "blue", "GBP" = "red")
```

```{r, echo=FALSE}
img <- (ggplot(data=ret, aes(x=data)) +
          geom_line(aes(y=`1USD`, color = "USD"), size=1.5) +
          geom_line(aes(y=`1EUR`, color = "EUR"), size=1.5) +
          geom_line(aes(y=`1GBP`, color = "GBP"), size=1.5) + 
          ggtitle("Wykresy kursów walut") +
          labs(x = "Data",y = "PLN", color = "Waluty") +
          scale_color_manual(values = colors)
)          
print(img)
```

# Rozdział 2. Tabela z notowaniami kursow USD, EUR, GBP
```{r , echo=FALSE, results="asis"}
rownames(ret) <- ret$Data
kable(ret, caption="Kursy walut za ostatnie 7 dni")
```